### ISSUE TITLE
Copy file from HDFS to Google Storage

### ISSUE THREAD

**Issue by jcoutino** [GoogleCloudPlatform/bigdata-interop#105]
I have the following code in Scala/Spark running on a Spark cluster. 
I am able to copy from local Unix file system to Google Storage (GS), however, unable to copy from HDFS to GS. I get the following error: 
> Wrong FS: hdfs://user/user101/test.csv, expected file:///

Any ideas how to resolve the wrong file system. Thanks.

```scala
val conf = spark.sparkContext.hadoopConfiguration
conf.set("google.cloud.auth.service.account.enable", "true")
conf.set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
conf.set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")

// . . .

val gcsFS = new Path("gs://folder/").getFileSystem(conf)
val gsPath = new Path("gs://folder/test.csv")
val filePathWorks = new Path("file:///home/user101/test.csv") // works with this path
val hdfsPath = new Path("hdfs://user/user101/test.csv") 

gcsFS.copyFromLocalFile(hdfsPath, gsPath)
```

**Comment by medb** [comment]
This could happen because HDFS is not configured properly.

See similar problem here:
https://stackoverflow.com/questions/27370168/hadoop-hdfs-wrong-fs-hdfs-0-0-0-09000-expected-file

Also, may you provide more details on where you running this job (Dataproc, EMR, or on-prem) and attach your `core-site.xml` and `hdfs-site.xml` configs?

**Comment by medb** [comment]
`FileSystem.copyFromLocalFile` method supports only copying from the local filesystem, that's why path should have `file:///` scheme.

If you want just to copy files between HDFS and GCS, you should use [distcp](https://hadoop.apache.org/docs/current/hadoop-distcp/DistCp.html).

**Comment by tejeskhandagale400** [comment]
how Copy file from HDFS to Google Storage using distcp in spark,  can you please  help me?

**Comment by medb** [comment]
DistCp is a [Hadoop CLI tool]() - you can not use it in Spark.

If you want to make a copy in Spark code, then you should use [`FileUtil`](https://github.com/apache/hadoop/blob/rel/release-3.2.1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileUtil.java) for this:

```java
FileUtil.copy(srcFs, srcPath, dstFs, dstPath, /* deleteSource= */ false, session.sparkContext().hadoopConfiguration());
```

Note that this could be quite slow if you are copying large amount of data.
