### ISSUE TITLE
Implementation of AccessTokenProvider for Vault GCP Secrets Backend

### ISSUE THREAD

**Issue by medzin** [GoogleCloudPlatform/bigdata-interop#109]
My company uses [Vault GCP Secrets Backend](https://github.com/hashicorp/vault-plugin-secrets-gcp) to manage service accounts and OAuth tokens on GCP. It looks like we have to provide our own implementation of AccessTokenProvider, so that we can use Vault in this library. Can we do pull request to this project or should it be a separate one on GitHub?

**Comment by medb** [comment]
At this point we do not plan to accept contribution for 3rd party AccessTokenProvider implementations.
