### ISSUE TITLE
gcs-connector pom contains unresolved hadoop.identifier property

### ISSUE THREAD

**Issue by coekie** [GoogleCloudPlatform/bigdata-interop#116]
Starting with version 1.9.0, the deployed pom for gcs-connector specifies its own version as `<version>1.9.0-${hadoop.identifier}</version>`. But that hadoop.identifier property cannot be resolved. The property is present in some profiles in the parent pom, but when you simply add gcs-connector as a dependency, those profiles aren't active.

This does not seem to be a problem for maven when resolving dependencies, but ivy cannot handle such a pom. Concretely in my case, I'm using pants, which also uses ivy to resolve external dependencies. Adding a dependency on a newer gcs-connector version gives this error:

java.text.ParseException: inconsistent module descriptor file found in 'https://[...]/com/google/cloud/bigdataoss/gcs-connector/1.9.2-hadoop2/gcs-connector-1.9.2-hadoop2.pom': bad revision: expected='1.9.2-hadoop2' found='1.9.2-${hadoop.identifier}';

It's fine to have those properties like that in the source, but the deployed version of the pom should not have properties that depend on profiles. This was still fine in 1.8.1. Compare:
* http://central.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/1.8.1-hadoop2/gcs-connector-1.8.1-hadoop2.pom has `<version>1.8.1-hadoop2</version>`
* http://central.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/1.9.0-hadoop2/gcs-connector-1.9.0-hadoop2.pom has `<version>1.9.0-${hadoop.identifier}</version>`

This is related to https://issues.apache.org/jira/browse/IVY-933 , but the suggested workaround there of setting checkconsistency to false does not help here. That makes it accept the version of the pom itself, but then it fails a little later to resolve its dependencies: `module not found: com.google.cloud.bigdataoss#util-hadoop;1.9.2-${hadoop.identifier}`. Note that in 1.8.1, that version used to be `${bigdataoss.util-hadoop.two.version}`, which is a property that _can_ be resolved.

**Comment by medb** [comment]
Thanks for report! I will check if it possible to rewrite version in pom.xml before releasing it to Maven Central. This could be a quite simple solution, but it will need to wait until 1.9.3 version will be released.

**Comment by medb** [comment]
Should be fixed in [1.9.3](https://github.com/GoogleCloudPlatform/bigdata-interop/releases/tag/v1.9.3) release.
