### ISSUE TITLE
BigQuery & custom queries : is there any replacement for deprecated BigQueryConfiguration.INPUT_QUERY_KEY?

### ISSUE THREAD

**Issue by norbjd** [GoogleCloudPlatform/bigdata-interop#125]
I noticed that `BigQueryConfiguration.INPUT_QUERY_KEY` is deprecated (and its usage is very weird : see below), but is there another way to use a custom Standard SQL query to retrieve data?

For now, I'm using `BigQueryConfiguration.INPUT_QUERY_KEY` like this (sample code in Scala) : 

```scala
val config: Configuration = sparkSession.sparkContext.hadoopConfiguration

val query = s"""
    |#standardSQL
    |SELECT ...
    |FROM myproject.mydataset.mytable
    |WHERE ...
""".stripMargin

config.set(BigQueryConfiguration.GCS_BUCKET_KEY, "mybucket")
config.set(BigQueryConfiguration.INPUT_QUERY_KEY, query)
BigQueryConfiguration.configureBigQueryInput(
    config,
    "myproject:mydataset.an_empty_temporary_table"
)

val bigQueryRDD: RDD[(LongWritable, JsonObject)] = sparkSession.sparkContext.newAPIHadoopRDD(
    config,
    classOf[GsonBigQueryInputFormat],
    classOf[LongWritable],
    classOf[JsonObject]
)

println(bigQueryRDD.count())
```

but it needs an empty table `myproject:mydataset.an_empty_temporary_table` having the same schema as my query result because calling `BigQueryConfiguration.configureBigQueryInput` is required.

I don't understand why it is necessary to declare this table. To me, it has no purpose because the job  just needs to dump query results on GCS with JSON format.

Is there a way to use a custom query without having to use an empty temporary table, or better, without using deprecated `BigQueryConfiguration.INPUT_QUERY_KEY`?

Thanks

**Comment by pmkc** [comment]
To the best of my knowledge BigQuery only supports outputting the results of large queries to another BigQuery table (not directly to GCS).

In any case functionality is deprecated. If you want to call BigQuery queries, I recommend using [google-cloud-bigquery](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-bigquery).

**Comment by norbjd** [comment]
@pmkc thanks for your answer.

However, I feel like using `google-cloud-bigquery` with Spark is not really adapted. How to take advantage of Spark parallelism if all data is first retrieved on the driver, and then parallelized? It may work on small tables, but not for huge ones (probably most cases since BigQuery is used to store huge amounts of data).

To me, not being able to use a custom query from the connector (at least, without having to make that query first, and then output the results in a new table) is a pity. Is there any plan to support that on the roadmap? I think it will be a great feature (even if behind the scenes, the output of the query is just dumped in another new temporary table, used as input for Spark).

Thanks

**Comment by pmkc** [comment]
@norbjd Sorry I missed you're follow-up comment. `google-cloud-bigquery` is optimized for querying BigQuery and saving the results inside of BigQuery itself. This connector is optimized from parallel reads from BigQuery. They can work perfectly together.

Run [this example code](https://github.com/googleapis/google-cloud-java/blob/65ca2f3d03d2744f59e5d4109c4efebe998a9514/google-cloud-examples/src/main/java/com/google/cloud/examples/bigquery/snippets/CloudSnippets.java#L104) to run your query and Save as a temp table and then use this connector to query it.

@mesunilag That may be weird, but it is how BigQuery (or any SQL engine works). It can only write query results to tables.
