### ISSUE TITLE
Cannot read and write in different locations: source: EU, destination: US

### ISSUE THREAD

**Issue by elha-da** [GoogleCloudPlatform/bigdata-interop#141]
Hi

Using ```com.google.cloud.hadoop.io.bigquery.BigQueryConfiguration.configureBigQueryInput``` I'm trying to load *BQ* table into *spark DataFrame*. 
The BQ table resides in EU location, so I set Hadoop configuration parameters : ```conf.set("mapred.bq.output.location", "EU")``` and ```conf.set("bq.staging_dataset.location", "EU")``` but the temporary bucket is even created in the US location and i get error: **Cannot read and write in different locations: source: EU, destination: US**.

is there any way to create to the EU location?

**Comment by medb** [comment]
You need to create GCS bucket manually in EU and set it as BQ connector bucket through `mapred.bq.gcs.bucket` [property](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/f3d3914dbe64d2f3609ec7a112624dbc071ad8e9/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/BigQueryConfiguration.java#L68).
