### ISSUE TITLE
Cannot specify nested BigQuery schema with `BigQueryTableFieldSchema`

### ISSUE THREAD

**Issue by jiayuanmasc** [GoogleCloudPlatform/bigdata-interop#144]
[`BigQueryTableFieldSchema`](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/output/BigQueryTableFieldSchema.java) wraps around [`TableFieldSchema`](https://developers.google.com/resources/api-libraries/documentation/bigquery/v2/java/latest/com/google/api/services/bigquery/model/TableSchema.html?is-external=true). However, it didn't provide an API to set nested schema fields for `RECORD` type like `TableFieldSchema#setFields`.

For example, the public dataset `bigquery-public-data:samples.github_nested` has a nested schema as follows.

![screen shot 2019-01-18 at 2 08 02 pm](https://user-images.githubusercontent.com/8022224/51415509-eec56100-1b2a-11e9-812c-5b5d82e0e7d9.png)

With `TableSchema`/`TableFieldSchema`, we are able to specify `payload` field as
```
new TableFieldSchema()
  .setName("payload")
  .setType("RECORD")
  .setFields(List(
     new TableFieldSchema().setName("action").setType("STRING"),
     new TableFieldSchema().setName("after").setType("STRING"),
     ...
  ))
```

The wrapper class [`BigQueryTableFieldSchema`](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/output/BigQueryTableFieldSchema.java) didn't provide a similar API like `setFields`. Therefore, such nested schema cannot be provided to `BigQueryOutputConfiguration.configure` as a typed Java object.

**Comment by functicons** [comment]
jiayuanmasc@ Thanks for the feedback, will fix it soon.
