### ISSUE TITLE
Spark Job marked as success when data is still being written to GCS

### ISSUE THREAD

**Issue by gridcellcoder** [GoogleCloudPlatform/bigdata-interop#145]
When using Spark on Kubernetes and the latest jar

`https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-latest-hadoop2.jar` (dont' know what version this corresponds to)

I have a spark job that writes about 10GB of data to GCS using DataFrame write

```
 df .write.json(path_to_gcs_bucket)
```
This job and stage completes 

![image](https://user-images.githubusercontent.com/17800018/51244468-1971b700-197d-11e9-9682-f021f1bc64e7.png)

but I can still see part files being written in the background:

```gs://mybucket/output/ZGM0YTg3Nzk2NDEwY2ViY2FhNTYwZTZi/part-00124-e86f3a48-72f7-4bf7-bdc4-328e97cdc7b1-c000.json```

The job is marked as success but there are still gcs writes going on in the background. This should update/report to the the job stage correctly and not be marked as `success`.

Once the writes have completed the spark context` stop()` is encountered and the job terminated.

using spark kubernetes `2.4.0` on gke `1.11.5-gke.5`

**Comment by medb** [comment]
Why do you think that his is GCS connector issues? GCS connector just a library used by Spark to read-write to GCS, its execution is fully controlled by Spark and it can not write anything by itself in background if Spark already finished job and/or task.

**Comment by gridcellcoder** [comment]
@medb good point though I though it might be related to how GCS connector reports progress back to Spark i.e. it may have marked the write as complete but still continues writing in the background. Given that I have no other alternatives (HDFS) to test on I was working on that assumption. I can test with a previous version of spark to see if that is still the case and might cross post this issue on Spark issues.

**Comment by gridcellcoder** [comment]
Also raised here https://issues.apache.org/jira/browse/SPARK-26647

**Comment by medb** [comment]
May you provide a screenshot with creation timestapms of these part files (using gsutil, for example) and job execution end time?

**Comment by gridcellcoder** [comment]
The final write job is shown below:

![image](https://user-images.githubusercontent.com/17800018/51675800-a5fb2580-1fcc-11e9-95ca-a7ec3910815c.png)

the job was submitted 11:23:08 and finished 3.6 mins later at 11:26:44 - shown under the completed section of the UI.

The bucket shows files being generated much later: 
![image](https://user-images.githubusercontent.com/17800018/51675889-ebb7ee00-1fcc-11e9-9174-b4f21a866d05.png)

up to 11:53:38

**Comment by medb** [comment]
Interesting, may you share the job itself or simplified version of it that reproduces the issue? I will try to reproduce and debug what's going on.
