### ISSUE TITLE
Compose acts as an append operation

### ISSUE THREAD

**Issue by Fokko** [GoogleCloudPlatform/bigdata-interop#162]
Hi,

I've been working on an implementation that relies on the compose operation. After testing I've noticed that the HDFS concat operation, implemented using a compose, acts as an append.
The following code will fail with an HTTP404 because the destination does not exists: https://gist.github.com/Fokko/2852f2738e0e4c9bef4d255111df423c

This feels weird to me since the overwrite flag is even set to true: https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl.java#L1948

Is there any way to just create or overwrite the destination. The current behavior feels weird to me.

Cheers, Fokko

**Comment by medb** [comment]
Agree, this is a little confusing, but apparently this is how [this operation works on HDFS](https://github.com/apache/hadoop/blob/b979fdde9907c36fd7da000b9fd64144d61b4306/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/server/namenode/FSNamesystem.java#L2068).

This was the reason for such implementation.

Are you using GCS IO directly, or through HDFS interface?

**Comment by Fokko** [comment]
Thanks for the quick response. We're using it through the HDFS interface. Right now we use:
```
// Create it first
ghfs.delete(dst, true);
ghfs.createNewFile(dst);
ghfs.concat(dst, paths);

for(Path p : paths) {
    try {
        ghfs.delete(p, true);
    } catch (IOException e) {
        // Don't care
    }
}
```
Which looks like quite a lot of calls for concatenating a file. I don't feel like appending to the first part of the file since if something happens, the source data might get corrupted. For example, what will happen if the concat fails in between? Therefore we're creating a new empty file, and then concatenating all the objects, and then doing the cleanup. Also, the final path is without a `.`, indicating the part files should be invisible until all the parts are uploaded.

**Comment by medb** [comment]
Even with an empty file `concat` is not atomic - it executes in batches of 32 files, so anyway you need to handle recovery correctly.

What if you copy first `path` to `dst` and concat rest of the `path`s to it, this way in case of failure you still will have all the source data to retry?
