### ISSUE TITLE
Getting an error in copying the google connector in hadoop directory.

### ISSUE THREAD

**Issue by Fahadsaadullahkhan** [GoogleCloudPlatform/bigdata-interop#193]
> Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/cloud/hadoop/fs/gcs/GoogleHadoopFileSystem : Unsupported major.minor version 52.0

Getting above exception when I'm copying `gcs-connector.jar` file in `/opt/cloudera/parcels/CDH/lib/hadoop`, it copied on 3 nodes but was getting the above exception while copying the connector on 4th node.

Any idea?

**Comment by lbergelson** [comment]
That sounds like a java version issue.  Are you sure you're running the version of java you expect on all of your nodes?

**Comment by medb** [comment]
It seems like you are using old Java version. GCS connectors requires Java 8. If you are using Java 7 then you will need to use GCS connector 1.6.10.

**Comment by Fahadsaadullahkhan** [comment]
I am using Jdk 8, made sure of it when I got that error

**Comment by Fahadsaadullahkhan** [comment]
node1 and node 4 has jdk "1.8.0_144"
node2 has jdk "1.8.0_151"
node 3 has jdk "1.8.0_191"

**Comment by medb** [comment]
It looks weird, because `52.0` refers to a Java 8 version.

Do you have only one JDK version installed on each node? How did you check JDK version that uses?
