### ISSUE TITLE
Hadoop connector disallows valid object names

### ISSUE THREAD

**Issue by chrisvittal** [GoogleCloudPlatform/bigdata-interop#197]
Object names with consecutive slashes in the middle are valid GCS names that may be referenced using `gsutil` and other tools. The linked code rejects valid inputs.

https://github.com/GoogleCloudPlatform/bigdata-interop/blob/ca86dbd9c010be12daa357170eb46786225d3b2f/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java#L1474-L1483

**Comment by medb** [comment]
It's a valid GCS object name but not a valid HDFS file name, that's why GCS connector that implements HDFS interface doesn't support such objects.
