### ISSUE TITLE
Issue while connecting GCS from AWS EMR using spark-job in cluster mode

### ISSUE THREAD

**Issue by danveer4686** [GoogleCloudPlatform/bigdata-interop#266]
I'm interested in reading some `gs://` URLs from a Spark Scala app running on AWS EMR in cluster mode.

I have service account credentials json to authenticate GCP connection, which is placed on HDFS path and passing it in `spark-submit` command in `--files` option. This file is being used in creating `SparkSession` object.

I created `SparkSession` object as below:
```scala
val spark = SparkSession.builder()
        .config("spark.default.parallelism", 4)
        .config("spark.sql.shuffle.partitions", 5)
        .config("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
        .config("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
        .config("fs.gs.project.id", "myProjectId")
        .config("fs.gs.auth.service.account.enable", "true")
        .config("google.cloud.auth.service.account.json.keyfile","gcs_service_account_credential.json")
        .enableHiveSupport()
        .getOrCreate()
```

I am running below `spark-submit` command on AWS EMR in cluster mode:
```
spark-submit --master yarn --deploy-mode cluster --driver-memory 4G --executor-memory 8G \
    --jars s3://bucket_path/lib/org.postgresql_postgresql-42.1.4.jar,s3://bucket_path/uat/gcp/bigquerylib.jar,s3://bucket_path/uat/gcp/sparklib.jar,s3://bucket_path/uat/gcp/gcs-connector-hadoop3-latest.jar,s3://bucket_path/uat/gcp/google-auth-library-credentials-0.17.1.jar \
    --conf 'spark.executor.extraJavaOptions=-XX:+UseG1GC -Dconfig.file=/home/hadoop/loaddata.properties' \
    --files hdfs:///gcs_service_account_credential.json \
    --class MainClass --name JobName \
    s3://bucket_path/uat/gcp/sparklib.jar args1 args2
```

My application is running as expected if I use client mode in spark submit command (`--deploy-mode client`)

But while running it on cluster mode (`--deploy-mode cluster`) job is failing with exit code 13.

**Comment by medb** [comment]
May you post exception that leads to failure in Spark Driver or executors? Without stack trace it's hard to tell what the cause is.

**Comment by danveer4686** [comment]
1. Checking that file exists on hdfs
`[hadoop@ip-172-13-13-201 ~]$ hdfs dfs -ls gcs_service_account_credential.json`
-rw-r--r--   1 hadoop hadoop       2321 2019-10-04 07:03 gcs_service_account_credential.json

2. Application logs after spark submit

`[hadoop@ip-172-13-13-201 ~]$ spark-submit --master yarn --deploy-mode cluster --driver-memory 4G --executor-memory 8G --jars s3://myBucket/jars/lib/org.postgresql_postgresql-42.1.4.jar,s3://myBucket/jars/uat/gcp/bigquerylib.jar,s3://myBucket/jars/uat/gcp/sparklib.jar,s3://myBucket/jars/uat/gcp/gcs-connector-hadoop3-latest.jar,s3://myBucket/jars/uat/gcp/google-auth-library-credentials-0.17.1.jar --conf 'spark.executor.extraJavaOptions=-XX:+UseG1GC -Dconfig.file=/home/hadoop/loaddata.properties' --files hdfs:///gcs_service_account_credential.json --class LoadData --name EtlJobAdvertiserMaster s3://myBucket/jars/uat/gcp/sparklib.jar args `
19/10/04 07:05:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/uat/gcp/sparklib.jar.
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/lib/org.postgresql_postgresql-42.1.4.jar.
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/uat/gcp/bigquerylib.jar.
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/uat/gcp/sparklib.jar.
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/uat/gcp/gcs-connector-hadoop3-latest.jar.
19/10/04 07:05:31 WARN DependencyUtils: Skip remote jar s3://myBucket/jars/uat/gcp/google-auth-library-credentials-0.17.1.jar.
19/10/04 07:05:31 INFO RMProxy: Connecting to ResourceManager at ip-172-13-13-201.ap-south-1.compute.internal/172.22.73.201:8032
19/10/04 07:05:31 INFO Client: Requesting a new application from cluster with 1 NodeManagers
19/10/04 07:05:31 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (11520 MB per container)
19/10/04 07:05:31 INFO Client: Will allocate AM container, with 4505 MB memory including 409 MB overhead
19/10/04 07:05:31 INFO Client: Setting up container launch context for our AM
19/10/04 07:05:31 INFO Client: Setting up the launch environment for our AM container
19/10/04 07:05:31 INFO Client: Preparing resources for our AM container
19/10/04 07:05:31 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
19/10/04 07:05:33 INFO Client: Uploading resource file:/mnt/tmp/spark-cb98971d-59e6-4ca6-95be-457fe5dd9df3/__spark_libs__9206679891378832584.zip -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/__spark_libs__9206679891378832584.zip
19/10/04 07:05:34 INFO Client: Uploading resource s3://myBucket/jars/uat/gcp/sparklib.jar -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/sparklib.jar
19/10/04 07:05:34 INFO S3NativeFileSystem: Opening 's3://myBucket/jars/uat/gcp/sparklib.jar' for reading
19/10/04 07:05:34 INFO Client: Uploading resource s3://myBucket/jars/lib/org.postgresql_postgresql-42.1.4.jar -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/org.postgresql_postgresql-42.1.4.jar
19/10/04 07:05:34 INFO S3NativeFileSystem: Opening 's3://myBucket/jars/lib/org.postgresql_postgresql-42.1.4.jar' for reading
19/10/04 07:05:34 INFO Client: Uploading resource s3://myBucket/jars/uat/gcp/bigquerylib.jar -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/bigquerylib.jar
19/10/04 07:05:34 INFO S3NativeFileSystem: Opening 's3://myBucket/jars/uat/gcp/bigquerylib.jar' for reading
19/10/04 07:05:35 WARN Client: Same path resource s3://myBucket/jars/uat/gcp/sparklib.jar added multiple times to distributed cache.
19/10/04 07:05:35 INFO Client: Uploading resource s3://myBucket/jars/uat/gcp/gcs-connector-hadoop3-latest.jar -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/gcs-connector-hadoop3-latest.jar
19/10/04 07:05:35 INFO S3NativeFileSystem: Opening 's3://myBucket/jars/uat/gcp/gcs-connector-hadoop3-latest.jar' for reading
19/10/04 07:05:35 INFO Client: Uploading resource s3://myBucket/jars/uat/gcp/google-auth-library-credentials-0.17.1.jar -> hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833/google-auth-library-credentials-0.17.1.jar
19/10/04 07:05:35 INFO S3NativeFileSystem: Opening 's3://myBucket/jars/uat/gcp/google-auth-library-credentials-0.17.1.jar' for reading
19/10/04 07:05:35 INFO Client: Source and destination file systems are the same. Not copying hdfs:/gcs_service_account_credential.json
19/10/04 07:05:35 INFO Client: Deleted staging directory hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/user/hadoop/.sparkStaging/application_1558439311639_0833
Exception in thread "main" java.io.FileNotFoundException: File does not exist: hdfs://ip-172-13-13-201.ap-south-1.compute.internal:8020/gcs_service_account_credential.json
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1444)
	at org.apache.hadoop.hdfs.DistributedFileSystem$27.doCall(DistributedFileSystem.java:1437)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1452)
	at org.apache.spark.deploy.yarn.ClientDistributedCacheManager$$anonfun$1.apply(ClientDistributedCacheManager.scala:71)
	at org.apache.spark.deploy.yarn.ClientDistributedCacheManager$$anonfun$1.apply(ClientDistributedCacheManager.scala:71)
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at org.apache.spark.deploy.yarn.ClientDistributedCacheManager.addResource(ClientDistributedCacheManager.scala:71)
	at org.apache.spark.deploy.yarn.Client.org$apache$spark$deploy$yarn$Client$$distribute$1(Client.scala:477)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10$$anonfun$apply$6.apply(Client.scala:597)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10$$anonfun$apply$6.apply(Client.scala:596)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:596)
	at org.apache.spark.deploy.yarn.Client$$anonfun$prepareLocalResources$10.apply(Client.scala:595)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:595)
	at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:863)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:177)
	at org.apache.spark.deploy.yarn.Client.run(Client.scala:1133)
	at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1525)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/04 07:05:35 INFO ShutdownHookManager: Shutdown hook called
19/10/04 07:05:35 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-cb98971d-59e6-4ca6-95be-457fe5dd9df3
19/10/04 07:05:35 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-dc1bbc01-bf4d-44c6-8a73-dffca6ee6cc1


3. Yarn appication logs are not generated

[hadoop@ip-172-13-13-201 ~]$ yarn logs -applicationId application_1558439311639_0833
19/10/04 07:12:57 INFO client.RMProxy: Connecting to ResourceManager at ip-172-13-13-201.ap-south-1.compute.internal/172.22.73.201:8032
Unable to get ApplicationState. Attempting to fetch logs directly from the filesystem.
/var/log/hadoop-yarn/apps/hadoop/logs/application_1558439311639_0833 does not exist.
Log aggregation has not completed or is not enabled.
[hadoop@ip-172-13-13-201 ~]$

**Comment by medb** [comment]
When you list file with `$ hdfs dfs -ls gcs_service_account_credential.json` command using relative path, it lists it in your HDFS home directory, but when you specifying it in the submit command using full path (`--files hdfs:///gcs_service_account_credential.json`) it looking for the file in the HDFS root.

To fix this issue you need to copy file to the HDFS root:
```
hdfs dfs -cp gcs_service_account_credential.json /gcs_service_account_credential.json
```
