### ISSUE TITLE
GCS slow overwrite parquet partition

### ISSUE THREAD

**Issue by pandareen** [GoogleCloudPlatform/bigdata-interop#270]
```
19/09/19 11:49:05 INFO FileUtils: deleting  gs://rbuck/folder/ggo/hive_table_any/month=6/year=2018/xyz=abc/part-00073-9dbb91f8-6041-402f-a093-1061bb9ffaa8.c000
19/09/19 11:51:17 INFO Hive: Replacing src:gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=6/year=2018/xyz=abc/part-00073-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, dest: gs://rbuck/folder/ggo/hive_table_any/month=6/year=2018/xyz=abc/part-00073-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, Status:true
19/09/19 11:51:17 INFO Hive: New loading path = gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=6/year=2018/xyz=abc with partSpec {month=6, year=2018, xyz=abc}
19/09/19 11:51:17 INFO FileUtils: deleting  gs://rbuck/folder/ggo/hive_table_any/month=2/year=2018/xyz=abc/part-00029-9dbb91f8-6041-402f-a093-1061bb9ffaa8.c000
19/09/19 11:53:21 INFO Hive: Replacing src:gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=2/year=2018/xyz=abc/part-00029-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, dest: gs://rbuck/folder/ggo/hive_table_any/month=2/year=2018/xyz=abc/part-00029-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, Status:true
19/09/19 11:53:21 INFO Hive: New loading path = gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=2/year=2018/xyz=abc with partSpec {month=2, year=2018, xyz=abc}
19/09/19 11:53:21 INFO FileUtils: deleting  gs://rbuck/folder/ggo/hive_table_any/month=8/year=2019/xyz=abc/part-00065-9dbb91f8-6041-402f-a093-1061bb9ffaa8.c000
19/09/19 11:55:22 INFO Hive: Replacing src:gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=8/year=2019/xyz=abc/part-00065-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, dest: gs://rbuck/folder/ggo/hive_table_any/month=8/year=2019/xyz=abc/part-00065-4a075b3d-61d3-46e9-8c28-ac2822ff0350.c000, Status:true
19/09/19 11:55:22 INFO Hive: New loading path = gs://rbuck/folder/ggo/hive_table_any/.hive-staging_hive_2019-09-19_10-31-36_055_8543786963981631342-1/-ext-10000/month=8/year=2019/xyz=abc with partSpec {month=8, year=2019, xyz=abc}
19/09/19 11:55:23 INFO FileUtils: deleting  gs://rbuck/folder/ggo/hive_table_any/month=9/year=2015/xyz=abc/part-00179-2a442cbd-d1b0-4484-9f44-7b33c5c1b57d.c000
```
 
I have a spark job that insert overwrites on hive table based on partitions month year and xyz.
The spark job itself takes 4 mins but after that the insert overwrite operation takes 2 hours with around 77 partitions. I am seeing that it is deleting files from google storage which is taking 2 mins per file. The actual size of the file is just in KBs. How do I speed up this deletion process?
Can we use the rsync tool?
Are there any configuration settings that will help? We have set up GCS with default parameters.

Side note: I used these settings and that brought down the deletion from 2 mins to 1 mins.
```
--conf spark.hadoop.fs.gs.batch.threads=16 
--conf spark.hadoop.parquet.enable.summary-metadata=false 
--conf spark.sql.parquet.mergeSchema=false 
--conf spark.sql.parquet.filterPushdown=true 
--conf spark.sql.hive.metastorePartitionPruning=true 
--conf spark.sql.parquet.cacheMetadata=true 
--conf spark.hadoop.fs.gs.performance.cache.enable=true 
--conf spark.hadoop.fs.gs.status.parallel.enable=true
```

**Comment by medb** [comment]
Most probably this is Sparks's Hive issue (it uses very old Hive 1.2.1 fork that doesn't have optimizations for object stores), if you will run the same query on Hive 2.3+ it should be much faster. May you try this?

Also next information will be useful:
1. What Spark version do you use?
2. What GCS connector version do you use?
2. Do you use Google Cloud Dataproc to run Spark or other Spark installation? If so, what Dataproc version do you use?
4. How many files in the these 77 partitions?
5. It will be useful for repro if you can provide a query example.

**Comment by pandareen** [comment]
Hello @medb 
I spawn a dataproc version https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.4
On top of that I don't customise any software inside. 
We are using hive 2.3.5
What Spark version do you use? 2.4.4
What GCS connector version do you use? 1.9.17-hadoop2
Do you use Google Cloud Dataproc to run Spark or other Spark installation? If so, what Dataproc version do you use? https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.4 [I use the dataproc dedicatedly, no resource sharing. I write an aggregation script in scala]
How many files in these 77 partitions? 1 file per partition ranging from 10mb to 100mb
It will be useful for repro if you can provide a query example.

I don't use query, I use scala code 
`dataframe.write.mode(SaveMode.Overwrite).insertInto(s"${table.name.value}")`

Hope this helps

**Comment by medb** [comment]
It's weird that it processing 77 files for 4 hours.

Few questions:
1. How many nested partition do you have? (e.g /year/month/day/etc)
2. May you post `gsutil` command output (`gsutil ls -al gs://baucket/path/to/partition`) for the one of partitions that you are overwriting?
3. May you post number of partition in your DataFrame before write:
   ```scala
   dataframe.rdd.partitions.size
   ``` 

Workaround could be to write data to the HDFS and after that copy/rsync it to GCS.

**Comment by pandareen** [comment]
1. Counted nested partitions combinations of <month><year><xyz> where <xyz> has 197 different values
```
$ hive --silent -e "show partitions db_name.table_name;" | wc -l
7727
```

2. 
```
$ gsutil ls -alh gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/
       0 B  2019-09-02T21:35:31Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1567460131592160  metageneration=1
       0 B  2019-09-23T02:49:31Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1569206971904191  metageneration=1
       0 B  2019-09-23T02:59:45Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1569207585525965  metageneration=1
       0 B  2019-09-23T04:16:06Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1569212166141543  metageneration=1
       0 B  2019-09-23T04:23:32Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1569212612357995  metageneration=1
       0 B  2019-09-30T15:53:18Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/#1569858798643391  metageneration=1
 52.79 MiB  2019-09-02T21:37:00Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/part-00121-0187e6fa-8ece-4be2-9e1e-bf2c266743d5.c000#1567460220081148  metageneration=1
 55.18 MiB  2019-08-17T07:42:38Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/part-00121-933ba613-0361-4553-b630-0f7381f12609.c000#1566027758261580  metageneration=1
 50.07 MiB  2019-09-12T15:57:37Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/part-00121-c1aadc5c-2d60-4672-b418-c0d7eb746084.c000#1568303857919287  metageneration=1
 57.99 MiB  2019-09-30T15:52:03Z  gs://bucket/db/name/table_name/month=5/year=2018/xyz=who/part-00121-fca557af-bfd8-4b98-ae0f-a006b3b286b7.c000#1569858723977787  metageneration=1
TOTAL: 10 objects, 226526287 bytes (216.03 MiB)
```

3. `dataframe.rdd.partitions.size` gives me 200

**Comment by pandareen** [comment]
@medb If you can provide me the most recommended way to setup GCS on dataproc then that would be great. Currently I am not making any custom configurations so any documentation other than the `README.md` would be good for starters

**Comment by medb** [comment]
This is a [known Spark issue](https://forums.databricks.com/questions/11102/insert-overwrite-in-spark-sqlhive-performance-is-v.html).

You can not fix it with any configuration in GCS connector because this is a Spark issue, you need to workaround it by avoiding `INSERT OVERWRITE` queries, or by performing them on HDFS instead of object store.

**Comment by medb** [comment]
One thing you can try, is if you are using dynamic partitioning then you can refactor your single query with dynamic partitioning to multiple queries with static partitioning (one query per partition each partition) - it could improve overall performance. You can find details on how to do this in this [post](https://medium.com/a-muggles-pensieve/writing-into-dynamic-partitions-using-spark-2e2b818a007a)

**Comment by pandareen** [comment]
Thanks for clarification. On the other hand, I've changed table type from parquet to ORC. Now instead of 170 mins it takes 7 mins. I'll close this as its not something from GCS end.
