### ISSUE TITLE
Support for querying federated tables in BigQuery

### ISSUE THREAD

**Issue by dennishuo** [GoogleCloudPlatform/bigdata-interop#32]
In this mode, the files may already be available in GCS, in which case the connector needs to query directly from GCS using the table metadata from BigQuery instead of issuing an extra export.

**Comment by elibixby** [comment]
This could also be used to alleviate the temporary files bug with failed jobs.

If the bigquery importer finds files in the location in which it wants to export, it looks for a cache file that specifies the timestamp at which the export was made, and uses the @<timestamp> decorator to only refetch new rows into GCS.
