### ISSUE TITLE
Issues loading project in IntelliJ

### ISSUE THREAD

**Issue by ryan-williams** [GoogleCloudPlatform/bigdata-interop#51]
Has anyone successfully gotten the project loaded into IntelliJ? My normal flow for doing so is resulting in IntelliJ not understanding the project's Maven-module structure.

Here's a screencast showing me importing it by pointing IntelliJ at its POM, selecting the `hadoop2` profile (the same failure happens whether I do this or not), and then IntelliJ not recognizing the `<module>` declarations in the root POM, and accordingly `hadoop` imports not being resolved in e.g. the `gcs` module:

![screencast gif showing intellij project-load flow](https://cl.ly/1d2z0B1o2w0B/sc3.gif)

I'm using:

```
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```

**Comment by medb** [comment]
[Recently](https://github.com/GoogleCloudPlatform/bigdata-interop/commit/76ceb340f0363d9c535dc2e2f5f765e02278d54a) we made project structure to be more friendly with IDEs, please give it a try.
