### ISSUE TITLE
v1.6.1 not shown on maven

### ISSUE THREAD

**Issue by jean-philippe-martin** [GoogleCloudPlatform/bigdata-interop#56]
The [release page](https://github.com/GoogleCloudPlatform/bigdata-interop/releases) shows that the latest release is v1.6.1 (in April), after 1.6.0 (December last year).

However if I go to the [mvnrepository page](https://mvnrepository.com/artifact/com.google.cloud.bigdataoss/gcs-connector), the last version it shows is 1.6.0 (December last year; same for [bigdataoss-parent](https://mvnrepository.com/artifact/com.google.cloud.bigdataoss/bigdataoss-parent)). It looks like 1.6.1 is missing?

Is this indicative of a problem, or perhaps I'm misunderstanding something?

**Comment by jean-philippe-martin** [comment]
Great, thank you!

**Comment by AngusDavis** [comment]
This should now be available on maven central.

**Comment by jean-philippe-martin** [comment]
Indeed, I can see it now. Thank you!
