### ISSUE TITLE
Mismatching `AbstractBigQueryInputFormat` expectations when specifying a query

### ISSUE THREAD

**Issue by jeffreyolchovy** [GoogleCloudPlatform/bigdata-interop#64]
When using `AbstractBigQueryInputFormat` and its descendants:

If a query is specified via `BigQueryConfiguration.INPUT_QUERY_KEY`, and the table from which you are issuing the query against is specified as `INPUT_TABLE_ID_KEY`, `QueryBasedExport.runQuery` will fail with `Already Exists: Table [tablename]`.

If you specify a new table name as `INPUT_TABLE_ID_KEY`, which will be used by `QueryBasedExport.runQuery` as `@param tableRef the table to write the results to`, the following failure will be experienced at `com.google.cloud.hadoop.io.bigquery.AbstractBigQueryInputFormat.constructExport(AbstractBigQueryInputFormat.java:191)`:
```
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: Table [tablename]",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Table [tablename]"
}
```

It appears there is a mismatch of expectations. Both `QueryBasedExport` and the other `Export`s use the same table name / table reference, but they have mutually exclusive preconditions.

`QueryBasedExport` expects the table to not exist, while the logic of the `AbstractBigQueryInputFormat` expects that same table reference to already exist (https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/bigquery/src/main/java/com/google/cloud/hadoop/io/bigquery/AbstractBigQueryInputFormat.java#L191).

**Comment by jeffreyolchovy** [comment]
My current workaround is to create a new empty table with REQUIRED fields set to NULLABLE on job start (before utiliziing the `InputFormat`), then destroy that table as part of the job cleanup.

**Comment by pmkc** [comment]
INPUT_QUERY_KEY has been deprecated for years and will probably not receive bug fixes.

I would encourage you to perform the query yourself at the top of your driver using [google-cloud-bigquery](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bigquery) or JDBC and then use the inputformat as normal.
