### ISSUE TITLE
BigQuery Connector for Spark: Query Views

### ISSUE THREAD

**Issue by juliankeppel** [GoogleCloudPlatform/bigdata-interop#65]
I tried the BigQuery Connector (0.10.2-hadoop2) for Spark (2.1.0) and it works fine for normal tables. 

But when I use it for BigQuery views, the Spark job shows following info message (in the aggregated yarn logs): `ShardedExportToCloudStorage: Table '<project>:<dataset>.<my-view-name>' to be exported has 0 rows and 0 bytes`. The job doesn't exit with any error.

Has anybody tried to query a view with the BigQuery connector from a Spark application before and encountered a similar problem?

**Comment by juliankeppel** [comment]
Please see also isse #68 because that was the original problem. This one here was only thought as workaround.

**Comment by gkohnen** [comment]
Having that problem as well, with the standard connector (sc.newAPIHadoopRDD): works fine for tables, silently fails for views.

**Comment by medb** [comment]
BigQuery API doesn't support export from a view:
https://stackoverflow.com/a/54482157/3227693

To query data in a view, you need first materialize it and after that query as a regular table:
https://stackoverflow.com/a/52999710/3227693
