### ISSUE TITLE
Support for setting User Agent

### ISSUE THREAD

**Issue by yu-talend** [GoogleCloudPlatform/bigdata-interop#78]
As a demand of Google Cloud Partner Data Reporting Policy for adding a User Agent String while using Google Cloud Services, is it possible to provide a new configuration property (sth. like _fs.google.user.agent.prefix_) to let users set it in Hadoop/Spark Configuration level ?

**Comment by pmkc** [comment]
I'm not familiar with that policy. Can you reference public documentation for your need?

In general we want to be able to track which Cloud Storage usage comes from which client (like the Hadoop Connector), and custom user agents might confuse that.

You can always recompile with your own user agent, but I understand that takes more effort and is not ideal.

**Comment by medb** [comment]
Please reopen, if it still relevant and you may share the policy.
