### ISSUE TITLE
Support for increasing timeouts?

### ISSUE THREAD

**Issue by nthelement** [GoogleCloudPlatform/bigdata-interop#80]
I'm having trouble uploading large files via the connector - once the file goes past 100MB I begin having upload timeouts. Further, it seems like there is no way to configure Google APIs defaults of 20 seconds.

**Comment by medb** [comment]
GCS connector supports HTTP requests configuration with properties:

    fs.gs.http.max.retry (default: 10)
    fs.gs.http.connect-timeout (default: 20000)
    fs.gs.http.read-timeout (default: 20000)
