### ISSUE TITLE
FEATURE: Pub/Sub - Support for Structured Streaming

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/bigdata-interop#84]
Hi,

Great new feature congrats!

However I was wondering if there is a plan to support the newer Spark *structured* streaming model (source and sink) as well as the older *dstream* method?

Cheers

**Comment by pmkc** [comment]
There is no plan at this time.

As stated by [Structures Streaming's documentation](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#fault-tolerance-semantics) "every streaming source is assumed to have offsets (similar to Kafka offsets, or Kinesis sequence numbers) to track the read position in the stream". This is not the model presented by Cloud Pub/Sub, where resent messages can appear in any subscriber.

One could get offsets by using a log structured store such as HDFS, Google Cloud Storage, or Kafka as an intermediate buffer. Something like:
`Cloud Pub/Sub -> Spark Streaming -> buffer -> Spark Structured Streaming`, with both Structured and regular streaming running in the same Spark application. I might add an example for that, but there is no plan to make that first class.

**Comment by sreenathraichur** [comment]
@pmkc When we expect the Pub/Sub will Support for Structured Streaming

**Comment by markus-braasch-ck** [comment]
Looking forward to Structured Streaming support for GCP Pub/Sub in Spark as well. :)

**Comment by sreenathraichur** [comment]
Hi Markus,

Yeah i ready give support on it. Can please call me once my mobile number
is +91-8121220440

Regards
R Sreenath

**Comment by darrenhaken** [comment]
Will this ever be supported?

**Comment by medb** [comment]
@darrenhaken We don't have plan for this at the moment. You can try to use [Apache Bahir](http://bahir.apache.org/) that supports both Pub/Sub and Spark Structured Streaming.

**Comment by joeyfaherty** [comment]
@medb Apache Bahir doesn't support Pub/Sub and Spark Structured Streaming.  It only supports a Spark DStream connector for Pub/Sub.

**Comment by medb** [comment]
@joeyfaherty please create a FR for Apache Bahir to add Spark Structured Streaming support to Pub/Sub connector.

**Comment by Ture2019** [comment]
Well, nowadays there is this...
https://github.com/googleapis/java-pubsublite-spark
