### ISSUE TITLE
Document all possible GCS connector properties in gcs-core-default.xml

### ISSUE THREAD

**Issue by pmkc** [GoogleCloudPlatform/bigdata-interop#88]
A number of properties are missing e.g. fs.gs.reportedPermissions.

Important properties should possibly also be called out in [the configuration section](../blob/master/gcs/INSTALL.md#configure-hadoop)

**Comment by medb** [comment]
Documented in #220:
https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/conf/gcs-core-default.xml
https://github.com/GoogleCloudPlatform/bigdata-interop/blob/master/gcs/CONFIGURATION.md
