### ISSUE TITLE
Any way to suppress this line when using HDFS commands? "INFO gcs.GoogleHadoopFileSystemBase"

### ISSUE THREAD

**Issue by gtaber** [GoogleCloudPlatform/bigdata-interop#89]
This line is prepended to every hdfs command's output. Love a way to suppress this.

[root@hadoophue1 hadoop-hdfs]# hdfs dfs -ls /
**18/02/08 16:29:59 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.0-hadoop2**
Found 1 items
drwxr-xr-x   - flume flume          0 2018-02-07 21:22 /flume

**Comment by medb** [comment]
You can change default Hadoop logging level from cli using single-line command:
```bash
HADOOP_ROOT_LOGGER=WARN hdfs dfs -ls /
```
or for ssh session:
```
export HADOOP_ROOT_LOGGER=WARN
hdfs dfs -ls /
```

To suppress logs only from `GoogleHadoopFileSystemBase` class, you can modify Hadoop Log4j config file (`/etc/hadoop/conf/log4j.properties`) and append this line to it:
```
log4j.logger.com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase=WARN
```
