### ISSUE TITLE
GCS connector doesn't retry some operations on IOException

### ISSUE THREAD

**Issue by actgardner** [GoogleCloudPlatform/bigdata-interop#98]
We use the GCS connector as a drop-in replacement for HDFS, but sometimes opening and reading from files will fail due to transient network errors. Looking at the `gcsio` codebase, it looks like [read has retry logic for IOExceptions](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/352f9e3aaf956bb0bbc3a39686a9819f70b4a2c2/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageReadChannel.java#L318), but [position](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/352f9e3aaf956bb0bbc3a39686a9819f70b4a2c2/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageReadChannel.java#L541) and [openStreamAndSetMetadata](https://github.com/GoogleCloudPlatform/bigdata-interop/blob/352f9e3aaf956bb0bbc3a39686a9819f70b4a2c2/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageReadChannel.java#L748) don't.

If the connection to GCS is interrupted these calls can hit a `SocketTimeoutException` or `SocketException`, which is safe to retry, but instead the exception is thrown. It seems like `position` and `openStreamAndSetMetadata` should have similar retry logic to `read` to handle `IOExceptions` caused by transient network errors.

**Comment by medb** [comment]
Fixed in https://github.com/GoogleCloudPlatform/bigdata-interop/commit/11157004847333fb3946e0eaccb5e3c0e703cd9e
