### ISSUE TITLE
Large unbounded thread growth related to gcsfs-timestamp-updates threads

### ISSUE THREAD

**Issue by andrewryder** [GoogleCloudPlatform/bigdata-interop#99]
We're running the GCS connector along side Dockerized YARN NodeManagers on Compute instances in GCP and have come across a peculiar issue related to gcsfs-timestamp-update threads.

It seems over time these threads never peel off, and eventually run up to 20k+ threads before the NM processes either end up having severe performance issues or simply OOM.

We are running version 1.8.1 of the connector and have tried disabling the parameter `fs.gs.parent.timestamp.update.enable` to see if that would alleviate some of the pressure, but it doesn't appear to have changed the growth.

As far as we can tell https://github.com/GoogleCloudPlatform/bigdata-interop/blob/v1.8.1/gcsio/src/main/java/com/google/cloud/hadoop/gcsio/GoogleCloudStorageFileSystem.java#L1371-L1393 is supposed to handle these threads from piling up but seems very few of these threads end up in a finished state (compared to many ending up in a WAITING state)

**Comment by medb** [comment]
This is a known issue in `GoogleHadoopFS` class (it doesn't have `close` method to cleanup threads), we expect to have a fix in next couple days.

**Comment by medb** [comment]
It will be back-ported to 1.6 branch and released as part of all Dataproc images (hopefully next week release).

We plan to release 1.9.0 as a next version in master branch, but it could take a little longer to do so, because I need to check if we have more changes in pipeline before cutting 1.9.0 release - there are already too many breaking changes for 1.8.2 release.

**Comment by medb** [comment]
This issue is fixed in https://github.com/GoogleCloudPlatform/bigdata-interop/commit/e12d4a01db2aeede5bb27c4b9f7b113de7c4d313

**Comment by medb** [comment]
GCS Connector 1.6.6 with back-ported fix has been released: https://github.com/GoogleCloudPlatform/bigdata-interop/releases/tag/v1.6.6

**Comment by andrewryder** [comment]
Thanks for the quick turnaround on this!
